2021-12-02 08:57:09,164 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-02 09:04:21,081 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-02 09:14:06,799 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-02 10:00:08,127 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-02 10:12:23,386 INFO 127.0.0.1 - - [02/Dec/2021 10:12:23] "POST /customer HTTP/1.1" 200 -
2021-12-02 10:22:20,273 INFO 127.0.0.1 - - [02/Dec/2021 10:22:20] "POST /customer HTTP/1.1" 200 -
2021-12-02 10:24:50,893 INFO 127.0.0.1 - - [02/Dec/2021 10:24:50] "GET /customer/1 HTTP/1.1" 200 -
2021-12-02 10:26:19,528 INFO 127.0.0.1 - - [02/Dec/2021 10:26:19] "GET /customers HTTP/1.1" 200 -
2021-12-02 10:31:57,058 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:31:57,069 INFO 127.0.0.1 - - [02/Dec/2021 10:31:57] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:32:12,227 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:32:12,228 INFO 127.0.0.1 - - [02/Dec/2021 10:32:12] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:34:44,295 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:34:44,297 INFO 127.0.0.1 - - [02/Dec/2021 10:34:44] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:35:17,475 INFO 127.0.0.1 - - [02/Dec/2021 10:35:17] "[31m[1mPATCH /customer/1 HTTP/1.1[0m" 400 -
2021-12-02 10:35:41,385 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:35:41,386 INFO 127.0.0.1 - - [02/Dec/2021 10:35:41] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:36:00,109 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:36:00,110 INFO 127.0.0.1 - - [02/Dec/2021 10:36:00] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:36:01,473 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:36:01,474 INFO 127.0.0.1 - - [02/Dec/2021 10:36:01] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:36:18,170 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:36:18,171 INFO 127.0.0.1 - - [02/Dec/2021 10:36:18] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:36:38,336 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:36:38,337 INFO 127.0.0.1 - - [02/Dec/2021 10:36:38] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:36:48,349 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:36:48,350 INFO 127.0.0.1 - - [02/Dec/2021 10:36:48] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:36:57,687 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:36:57,687 INFO 127.0.0.1 - - [02/Dec/2021 10:36:57] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:37:39,106 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:37:39,109 INFO 127.0.0.1 - - [02/Dec/2021 10:37:39] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:39:42,688 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:39:42,690 INFO 127.0.0.1 - - [02/Dec/2021 10:39:42] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:39:58,608 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:39:58,609 INFO 127.0.0.1 - - [02/Dec/2021 10:39:58] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:40:13,596 ERROR Exception on /customer/1 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:40:13,597 INFO 127.0.0.1 - - [02/Dec/2021 10:40:13] "[35m[1mPATCH /customer/1 HTTP/1.1[0m" 500 -
2021-12-02 10:42:40,470 INFO 127.0.0.1 - - [02/Dec/2021 10:42:40] "DELETE /customer/1 HTTP/1.1" 200 -
2021-12-02 10:43:39,724 ERROR Exception on /customer/2 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:43:39,727 INFO 127.0.0.1 - - [02/Dec/2021 10:43:39] "[35m[1mPATCH /customer/2 HTTP/1.1[0m" 500 -
2021-12-02 10:43:53,031 ERROR Exception on /customer/2 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:43:53,032 INFO 127.0.0.1 - - [02/Dec/2021 10:43:53] "[35m[1mPATCH /customer/2 HTTP/1.1[0m" 500 -
2021-12-02 10:44:04,363 ERROR Exception on /customer/2 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:44:04,364 INFO 127.0.0.1 - - [02/Dec/2021 10:44:04] "[35m[1mPATCH /customer/2 HTTP/1.1[0m" 500 -
2021-12-02 10:44:16,272 ERROR Exception on /customer/2 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:44:16,273 INFO 127.0.0.1 - - [02/Dec/2021 10:44:16] "[35m[1mPATCH /customer/2 HTTP/1.1[0m" 500 -
2021-12-02 10:44:26,106 ERROR Exception on /customer/2 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 72, in update_customer_by_id
    customer_data["firstName"],
KeyError: 'firstName'
2021-12-02 10:44:26,106 INFO 127.0.0.1 - - [02/Dec/2021 10:44:26] "[35m[1mPATCH /customer/2 HTTP/1.1[0m" 500 -
2021-12-02 10:44:40,906 INFO 127.0.0.1 - - [02/Dec/2021 10:44:40] "PATCH /customer/2 HTTP/1.1" 200 -
2021-12-02 12:04:10,132 INFO 127.0.0.1 - - [02/Dec/2021 12:04:10] "DELETE /customer/2 HTTP/1.1" 200 -
2021-12-02 12:04:36,176 INFO 127.0.0.1 - - [02/Dec/2021 12:04:36] "POST /customer HTTP/1.1" 200 -
2021-12-03 17:14:16,469 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:15:24,920 ERROR Exception on /account [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 104, in create_account
    account_data["bankAccountId"],
TypeError: 'NoneType' object is not subscriptable
2021-12-03 17:15:24,926 INFO 127.0.0.1 - - [03/Dec/2021 17:15:24] "[35m[1mPOST /account HTTP/1.1[0m" 500 -
2021-12-03 17:15:34,596 ERROR Exception on /account [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 104, in create_account
    account_data["bankAccountId"],
TypeError: 'NoneType' object is not subscriptable
2021-12-03 17:15:34,598 INFO 127.0.0.1 - - [03/Dec/2021 17:15:34] "[35m[1mPOST /account HTTP/1.1[0m" 500 -
2021-12-03 17:15:40,796 ERROR Exception on /account [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 104, in create_account
    account_data["bankAccountId"],
TypeError: 'NoneType' object is not subscriptable
2021-12-03 17:15:40,797 INFO 127.0.0.1 - - [03/Dec/2021 17:15:40] "[35m[1mPOST /account HTTP/1.1[0m" 500 -
2021-12-03 17:16:44,183 INFO 127.0.0.1 - - [03/Dec/2021 17:16:44] "POST /account HTTP/1.1" 200 -
2021-12-03 17:17:21,175 INFO 127.0.0.1 - - [03/Dec/2021 17:17:21] "POST /account HTTP/1.1" 200 -
2021-12-03 17:17:46,446 INFO 127.0.0.1 - - [03/Dec/2021 17:17:46] "POST /account HTTP/1.1" 200 -
2021-12-03 17:25:51,335 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:29:07,747 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:33:51,466 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:34:34,017 ERROR Exception on /deposit/5 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:34:34,020 INFO 127.0.0.1 - - [03/Dec/2021 17:34:34] "[35m[1mPATCH /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 17:35:33,270 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:35:43,453 ERROR Exception on /deposit/5 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:35:43,468 INFO 127.0.0.1 - - [03/Dec/2021 17:35:43] "[35m[1mPATCH /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 17:37:33,314 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:37:51,271 ERROR Exception on /deposit/5/100 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 1 required positional argument: 'self'
2021-12-03 17:37:51,274 INFO 127.0.0.1 - - [03/Dec/2021 17:37:51] "[35m[1mPATCH /deposit/5/100 HTTP/1.1[0m" 500 -
2021-12-03 17:37:52,857 ERROR Exception on /deposit/5/100 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 1 required positional argument: 'self'
2021-12-03 17:37:52,861 INFO 127.0.0.1 - - [03/Dec/2021 17:37:52] "[35m[1mPATCH /deposit/5/100 HTTP/1.1[0m" 500 -
2021-12-03 17:41:45,266 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:42:11,260 ERROR Exception on /deposit/5/100 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 1 required positional argument: 'self'
2021-12-03 17:42:11,264 INFO 127.0.0.1 - - [03/Dec/2021 17:42:11] "[35m[1mPATCH /deposit/5/100 HTTP/1.1[0m" 500 -
2021-12-03 17:42:18,211 INFO 127.0.0.1 - - [03/Dec/2021 17:42:18] "[33mPATCH /deposit/5 HTTP/1.1[0m" 404 -
2021-12-03 17:42:33,982 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:42:38,474 ERROR Exception on /deposit/5 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:42:38,477 INFO 127.0.0.1 - - [03/Dec/2021 17:42:38] "[35m[1mPATCH /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 17:43:33,895 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:43:41,579 ERROR Exception on /deposit/5 [PATCH]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:43:41,587 INFO 127.0.0.1 - - [03/Dec/2021 17:43:41] "[35m[1mPATCH /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 17:50:16,693 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:50:42,218 ERROR Exception on /deposit/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:50:42,221 INFO 127.0.0.1 - - [03/Dec/2021 17:50:42] "[35m[1mPOST /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 17:51:15,717 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:51:19,421 ERROR Exception on /deposit/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:51:19,424 INFO 127.0.0.1 - - [03/Dec/2021 17:51:19] "[35m[1mPOST /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 17:52:46,853 ERROR Exception on /deposit/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:52:46,854 INFO 127.0.0.1 - - [03/Dec/2021 17:52:46] "[35m[1mPOST /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 17:58:04,256 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:58:49,205 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 17:58:59,773 ERROR Exception on /deposit/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 2 required positional arguments: 'self' and 'deposit_amount'
2021-12-03 17:58:59,779 INFO 127.0.0.1 - - [03/Dec/2021 17:58:59] "[35m[1mPOST /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 18:07:14,791 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 18:07:17,240 ERROR Exception on /deposit/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: deposit_into_account_by_id() missing 1 required positional argument: 'self'
2021-12-03 18:07:17,244 INFO 127.0.0.1 - - [03/Dec/2021 18:07:17] "[35m[1mPOST /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 18:08:27,275 INFO 127.0.0.1 - - [03/Dec/2021 18:08:27] "POST /account HTTP/1.1" 200 -
2021-12-03 18:15:22,116 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 18:15:44,188 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 18:16:19,243 ERROR Exception on /deposit/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 120, in deposit_into_account_by_id
    deposit_amount = deposit_raw["depositAmount"]
KeyError: 'depositAmount'
2021-12-03 18:16:19,251 INFO 127.0.0.1 - - [03/Dec/2021 18:16:19] "[35m[1mPOST /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 18:17:31,518 INFO 127.0.0.1 - - [03/Dec/2021 18:17:31] "POST /deposit/5 HTTP/1.1" 200 -
2021-12-03 20:42:29,836 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 20:46:59,670 INFO 127.0.0.1 - - [03/Dec/2021 20:46:59] "POST /withdraw/5 HTTP/1.1" 200 -
2021-12-03 20:48:40,641 INFO 127.0.0.1 - - [03/Dec/2021 20:48:40] "POST /withdraw/5 HTTP/1.1" 200 -
2021-12-03 21:32:31,213 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 21:34:56,014 INFO 127.0.0.1 - - [03/Dec/2021 21:34:56] "POST /transfer/5/6 HTTP/1.1" 200 -
2021-12-03 21:35:47,396 INFO 127.0.0.1 - - [03/Dec/2021 21:35:47] "POST /transfer/5/6 HTTP/1.1" 200 -
2021-12-03 21:36:32,194 INFO 127.0.0.1 - - [03/Dec/2021 21:36:32] "POST /transfer/6/5 HTTP/1.1" 200 -
2021-12-03 21:46:27,655 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 21:49:12,161 INFO 127.0.0.1 - - [03/Dec/2021 21:49:12] "GET /account/6 HTTP/1.1" 200 -
2021-12-03 21:49:45,587 INFO 127.0.0.1 - - [03/Dec/2021 21:49:45] "GET /account/60 HTTP/1.1" 200 -
2021-12-03 22:20:19,465 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 22:21:59,844 INFO 127.0.0.1 - - [03/Dec/2021 22:21:59] "GET /accounts HTTP/1.1" 200 -
2021-12-03 22:23:07,155 INFO 127.0.0.1 - - [03/Dec/2021 22:23:07] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 22:27:17,310 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 22:29:25,580 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 22:33:14,865 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 22:36:51,623 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 22:36:56,604 INFO 127.0.0.1 - - [03/Dec/2021 22:36:56] "POST /customer HTTP/1.1" 200 -
2021-12-03 22:37:28,607 INFO 127.0.0.1 - - [03/Dec/2021 22:37:28] "POST /customer HTTP/1.1" 200 -
2021-12-03 22:37:53,569 INFO 127.0.0.1 - - [03/Dec/2021 22:37:53] "POST /customer HTTP/1.1" 200 -
2021-12-03 22:38:21,452 INFO 127.0.0.1 - - [03/Dec/2021 22:38:21] "GET /customer/1 HTTP/1.1" 200 -
2021-12-03 22:38:29,174 INFO 127.0.0.1 - - [03/Dec/2021 22:38:29] "GET /customers HTTP/1.1" 200 -
2021-12-03 22:39:02,199 INFO 127.0.0.1 - - [03/Dec/2021 22:39:02] "PATCH /customer/2 HTTP/1.1" 200 -
2021-12-03 22:39:40,422 INFO 127.0.0.1 - - [03/Dec/2021 22:39:40] "POST /customer HTTP/1.1" 200 -
2021-12-03 22:40:02,787 INFO 127.0.0.1 - - [03/Dec/2021 22:40:02] "DELETE /customer/4 HTTP/1.1" 200 -
2021-12-03 22:40:19,725 INFO 127.0.0.1 - - [03/Dec/2021 22:40:19] "POST /account HTTP/1.1" 200 -
2021-12-03 22:40:40,951 INFO 127.0.0.1 - - [03/Dec/2021 22:40:40] "POST /account HTTP/1.1" 200 -
2021-12-03 22:41:14,744 INFO 127.0.0.1 - - [03/Dec/2021 22:41:14] "POST /account HTTP/1.1" 200 -
2021-12-03 22:43:08,225 INFO 127.0.0.1 - - [03/Dec/2021 22:43:08] "POST /account HTTP/1.1" 200 -
2021-12-03 22:44:05,701 INFO 127.0.0.1 - - [03/Dec/2021 22:44:05] "POST /account HTTP/1.1" 200 -
2021-12-03 22:44:12,254 INFO 127.0.0.1 - - [03/Dec/2021 22:44:12] "POST /account HTTP/1.1" 200 -
2021-12-03 22:49:08,834 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 22:49:22,736 INFO 127.0.0.1 - - [03/Dec/2021 22:49:22] "POST /account HTTP/1.1" 200 -
2021-12-03 22:49:29,387 INFO 127.0.0.1 - - [03/Dec/2021 22:49:29] "POST /account HTTP/1.1" 200 -
2021-12-03 22:49:41,914 ERROR Exception on /deposit/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 128, in deposit_into_account_by_id
    account_to_deposit = bank_account_service.service_get_account_by_id(int(bank_account_id))
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 59, in service_get_account_by_id
    raise AccountDoesNotExist("Bank account does not exist!")
custom_exceptions.account_does_not_exist.AccountDoesNotExist: Bank account does not exist!
2021-12-03 22:49:41,920 INFO 127.0.0.1 - - [03/Dec/2021 22:49:41] "[35m[1mPOST /deposit/5 HTTP/1.1[0m" 500 -
2021-12-03 22:50:06,798 ERROR Exception on /withdraw/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 144, in withdraw_from_account_by_id
    withdraw_from_account = bank_account_service.service_get_account_by_id(int(bank_account_id))
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 59, in service_get_account_by_id
    raise AccountDoesNotExist("Bank account does not exist!")
custom_exceptions.account_does_not_exist.AccountDoesNotExist: Bank account does not exist!
2021-12-03 22:50:06,800 INFO 127.0.0.1 - - [03/Dec/2021 22:50:06] "[35m[1mPOST /withdraw/5 HTTP/1.1[0m" 500 -
2021-12-03 22:50:22,727 INFO 127.0.0.1 - - [03/Dec/2021 22:50:22] "POST /customer HTTP/1.1" 200 -
2021-12-03 22:50:38,413 INFO 127.0.0.1 - - [03/Dec/2021 22:50:38] "POST /account HTTP/1.1" 200 -
2021-12-03 22:50:43,746 ERROR Exception on /transfer/6/5 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 163, in transfer_money_between_accounts_by_id
    sending = bank_account_service.service_get_account_by_id(int(bank_account_id))
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 59, in service_get_account_by_id
    raise AccountDoesNotExist("Bank account does not exist!")
custom_exceptions.account_does_not_exist.AccountDoesNotExist: Bank account does not exist!
2021-12-03 22:50:43,747 INFO 127.0.0.1 - - [03/Dec/2021 22:50:43] "[35m[1mPOST /transfer/6/5 HTTP/1.1[0m" 500 -
2021-12-03 22:51:10,063 ERROR Exception on /deposit/1 [POST]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 128, in deposit_into_account_by_id
    account_to_deposit = bank_account_service.service_get_account_by_id(int(bank_account_id))
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 59, in service_get_account_by_id
    raise AccountDoesNotExist("Bank account does not exist!")
custom_exceptions.account_does_not_exist.AccountDoesNotExist: Bank account does not exist!
2021-12-03 22:51:10,065 INFO 127.0.0.1 - - [03/Dec/2021 22:51:10] "[35m[1mPOST /deposit/1 HTTP/1.1[0m" 500 -
2021-12-03 22:57:12,827 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 22:57:21,443 INFO 127.0.0.1 - - [03/Dec/2021 22:57:21] "POST /account HTTP/1.1" 200 -
2021-12-03 22:57:29,004 INFO 127.0.0.1 - - [03/Dec/2021 22:57:29] "POST /account HTTP/1.1" 200 -
2021-12-03 22:57:49,719 INFO 127.0.0.1 - - [03/Dec/2021 22:57:49] "POST /account HTTP/1.1" 200 -
2021-12-03 23:02:08,891 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:02:30,119 INFO 127.0.0.1 - - [03/Dec/2021 23:02:30] "POST /account HTTP/1.1" 200 -
2021-12-03 23:02:37,148 INFO 127.0.0.1 - - [03/Dec/2021 23:02:37] "POST /account HTTP/1.1" 200 -
2021-12-03 23:02:43,564 INFO 127.0.0.1 - - [03/Dec/2021 23:02:43] "POST /account HTTP/1.1" 200 -
2021-12-03 23:02:45,287 INFO 127.0.0.1 - - [03/Dec/2021 23:02:45] "POST /account HTTP/1.1" 200 -
2021-12-03 23:02:53,884 INFO 127.0.0.1 - - [03/Dec/2021 23:02:53] "POST /deposit/1 HTTP/1.1" 200 -
2021-12-03 23:03:08,115 INFO 127.0.0.1 - - [03/Dec/2021 23:03:08] "POST /withdraw/1 HTTP/1.1" 200 -
2021-12-03 23:03:18,805 INFO 127.0.0.1 - - [03/Dec/2021 23:03:18] "GET /accounts HTTP/1.1" 200 -
2021-12-03 23:03:24,372 INFO 127.0.0.1 - - [03/Dec/2021 23:03:24] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 23:07:10,802 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:07:23,058 INFO 127.0.0.1 - - [03/Dec/2021 23:07:23] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 23:07:28,860 INFO 127.0.0.1 - - [03/Dec/2021 23:07:28] "GET /accounts/3 HTTP/1.1" 200 -
2021-12-03 23:13:56,281 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:14:04,356 INFO 127.0.0.1 - - [03/Dec/2021 23:14:04] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 23:14:12,405 INFO 127.0.0.1 - - [03/Dec/2021 23:14:12] "GET /accounts/3 HTTP/1.1" 200 -
2021-12-03 23:21:43,327 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:21:50,838 ERROR Exception on /accounts/1 [GET]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 201, in get_all_customer_bank_accounts_by_id
    accounts = bank_account_service.service_get_all_customer_bank_accounts_by_id(int(customer_id))
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 68, in service_get_all_customer_bank_accounts_by_id
    customer_accounts = list(filter(lambda account: account[1] == customer_id, accounts))
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 68, in <lambda>
    customer_accounts = list(filter(lambda account: account[1] == customer_id, accounts))
TypeError: 'BankAccount' object is not subscriptable
2021-12-03 23:21:50,843 INFO 127.0.0.1 - - [03/Dec/2021 23:21:50] "[35m[1mGET /accounts/1 HTTP/1.1[0m" 500 -
2021-12-03 23:27:33,117 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:27:44,127 INFO 127.0.0.1 - - [03/Dec/2021 23:27:44] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 23:30:26,903 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:30:30,428 INFO 127.0.0.1 - - [03/Dec/2021 23:30:30] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 23:30:35,625 INFO 127.0.0.1 - - [03/Dec/2021 23:30:35] "GET /accounts/3 HTTP/1.1" 200 -
2021-12-03 23:31:11,811 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:31:18,254 INFO 127.0.0.1 - - [03/Dec/2021 23:31:18] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 23:32:02,407 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:33:00,785 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:33:07,966 INFO 127.0.0.1 - - [03/Dec/2021 23:33:07] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-03 23:33:18,911 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:34:20,888 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:36:16,229 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-03 23:36:20,563 INFO 127.0.0.1 - - [03/Dec/2021 23:36:20] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 10:58:33,317 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 10:58:41,953 INFO 127.0.0.1 - - [04/Dec/2021 10:58:41] "GET /customer/1 HTTP/1.1" 200 -
2021-12-04 10:58:48,871 INFO 127.0.0.1 - - [04/Dec/2021 10:58:48] "GET /customer/3 HTTP/1.1" 200 -
2021-12-04 10:59:42,383 INFO 127.0.0.1 - - [04/Dec/2021 10:59:42] "GET /customer/30 HTTP/1.1" 200 -
2021-12-04 11:00:26,035 INFO 127.0.0.1 - - [04/Dec/2021 11:00:26] "DELETE /account/6 HTTP/1.1" 200 -
2021-12-04 11:01:04,770 ERROR Exception on /account/6 [DELETE]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 215, in service_delete_account_by_id
    account_to_delete = bank_account_service.service_get_account_by_id(int(bank_account_id))
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 58, in service_get_account_by_id
    raise AccountDoesNotExist("Bank account does not exist!")
custom_exceptions.account_does_not_exist.AccountDoesNotExist: Bank account does not exist!
2021-12-04 11:01:04,780 INFO 127.0.0.1 - - [04/Dec/2021 11:01:04] "[35m[1mDELETE /account/6 HTTP/1.1[0m" 500 -
2021-12-04 11:23:04,160 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:23:15,347 INFO 127.0.0.1 - - [04/Dec/2021 11:23:15] "DELETE /account/6 HTTP/1.1" 200 -
2021-12-04 11:25:12,853 INFO 127.0.0.1 - - [04/Dec/2021 11:25:12] "POST /account HTTP/1.1" 200 -
2021-12-04 11:31:30,376 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:31:43,063 ERROR Exception on /account/7 [DELETE]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 216, in service_delete_account_by_id
    deleted = bank_account_service.service_delete_account_by_id(account_to_delete)
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 74, in service_delete_account_by_id
    account = self.bank_account_dao.get_account_by_id(bank_account_id)
  File "/Users/dlanderos/PycharmProjects/Project_0/data_access_layer/implementation_classes/bank_account_postgres_dao.py", line 48, in get_account_by_id
    cursor.execute(sql, [bank_account_id])
psycopg2.ProgrammingError: can't adapt type 'BankAccount'
2021-12-04 11:31:43,074 INFO 127.0.0.1 - - [04/Dec/2021 11:31:43] "[35m[1mDELETE /account/7 HTTP/1.1[0m" 500 -
2021-12-04 11:35:58,387 INFO 127.0.0.1 - - [04/Dec/2021 11:35:58] "GET /account/2 HTTP/1.1" 200 -
2021-12-04 11:36:14,422 INFO 127.0.0.1 - - [04/Dec/2021 11:36:14] "GET /account/3 HTTP/1.1" 200 -
2021-12-04 11:42:27,654 INFO 127.0.0.1 - - [04/Dec/2021 11:42:27] "GET /account/7 HTTP/1.1" 200 -
2021-12-04 11:44:33,680 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:44:49,384 INFO 127.0.0.1 - - [04/Dec/2021 11:44:49] "DELETE /account/7 HTTP/1.1" 200 -
2021-12-04 11:45:33,733 INFO 127.0.0.1 - - [04/Dec/2021 11:45:33] "DELETE /account/2 HTTP/1.1" 200 -
2021-12-04 11:46:46,680 INFO 127.0.0.1 - - [04/Dec/2021 11:46:46] "GET /account/2 HTTP/1.1" 200 -
2021-12-04 11:46:51,839 INFO 127.0.0.1 - - [04/Dec/2021 11:46:51] "DELETE /account/2 HTTP/1.1" 200 -
2021-12-04 11:47:44,360 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:47:48,066 ERROR Exception on /account/2 [DELETE]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 216, in service_delete_account_by_id
    deleted = bank_account_service.service_delete_account_by_id(account_to_delete)
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 74, in service_delete_account_by_id
    account = self.bank_account_dao.get_account_by_id(bank_account_id)
  File "/Users/dlanderos/PycharmProjects/Project_0/data_access_layer/implementation_classes/bank_account_postgres_dao.py", line 48, in get_account_by_id
    cursor.execute(sql, [bank_account_id])
psycopg2.ProgrammingError: can't adapt type 'BankAccount'
2021-12-04 11:47:48,073 INFO 127.0.0.1 - - [04/Dec/2021 11:47:48] "[35m[1mDELETE /account/2 HTTP/1.1[0m" 500 -
2021-12-04 11:49:09,278 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:49:13,232 INFO 127.0.0.1 - - [04/Dec/2021 11:49:13] "DELETE /account/2 HTTP/1.1" 200 -
2021-12-04 11:49:33,078 INFO 127.0.0.1 - - [04/Dec/2021 11:49:33] "GET /accounts HTTP/1.1" 200 -
2021-12-04 11:49:42,868 INFO 127.0.0.1 - - [04/Dec/2021 11:49:42] "GET /account/7 HTTP/1.1" 200 -
2021-12-04 11:49:51,420 INFO 127.0.0.1 - - [04/Dec/2021 11:49:51] "DELETE /account/7 HTTP/1.1" 200 -
2021-12-04 11:51:14,315 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:51:20,963 ERROR Exception on /account/7 [DELETE]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 216, in service_delete_account_by_id
    deleted = bank_account_service.service_delete_account_by_id(account_to_delete)
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 74, in service_delete_account_by_id
    return self.bank_account_dao.delete_account_by_id(bank_account_id)
  File "/Users/dlanderos/PycharmProjects/Project_0/data_access_layer/implementation_classes/bank_account_postgres_dao.py", line 76, in delete_account_by_id
    cursor.execute(sql, [bank_account_id])
psycopg2.ProgrammingError: can't adapt type 'BankAccount'
2021-12-04 11:51:20,969 INFO 127.0.0.1 - - [04/Dec/2021 11:51:20] "[35m[1mDELETE /account/7 HTTP/1.1[0m" 500 -
2021-12-04 11:56:30,272 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:56:34,744 ERROR Exception on /account/7 [DELETE]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dlanderos/PycharmProjects/Project_0/main.py", line 215, in service_delete_account_by_id
    deleted = bank_account_service.service_delete_account_by_id(account_to_delete)
  File "/Users/dlanderos/PycharmProjects/Project_0/service_layer/implemententation_service/bank_account_postgres_service.py", line 74, in service_delete_account_by_id
    return self.bank_account_dao.delete_account_by_id(bank_account_id)
  File "/Users/dlanderos/PycharmProjects/Project_0/data_access_layer/implementation_classes/bank_account_postgres_dao.py", line 76, in delete_account_by_id
    cursor.execute(sql, [bank_account_id])
psycopg2.ProgrammingError: can't adapt type 'BankAccount'
2021-12-04 11:56:34,750 INFO 127.0.0.1 - - [04/Dec/2021 11:56:34] "[35m[1mDELETE /account/7 HTTP/1.1[0m" 500 -
2021-12-04 11:56:47,709 INFO 127.0.0.1 - - [04/Dec/2021 11:56:47] "GET /account/2 HTTP/1.1" 200 -
2021-12-04 11:57:48,987 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:57:54,983 INFO 127.0.0.1 - - [04/Dec/2021 11:57:54] "DELETE /account/7 HTTP/1.1" 200 -
2021-12-04 11:58:07,804 INFO 127.0.0.1 - - [04/Dec/2021 11:58:07] "DELETE /account/7 HTTP/1.1" 200 -
2021-12-04 11:58:24,521 INFO 127.0.0.1 - - [04/Dec/2021 11:58:24] "DELETE /account/7 HTTP/1.1" 200 -
2021-12-04 11:58:50,560 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 11:58:56,609 INFO 127.0.0.1 - - [04/Dec/2021 11:58:56] "DELETE /account/7 HTTP/1.1" 200 -
2021-12-04 12:04:54,805 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 12:05:02,894 INFO 127.0.0.1 - - [04/Dec/2021 12:05:02] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 12:06:51,134 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 12:06:55,753 INFO 127.0.0.1 - - [04/Dec/2021 12:06:55] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 12:07:01,469 INFO 127.0.0.1 - - [04/Dec/2021 12:07:01] "GET /accounts/10 HTTP/1.1" 200 -
2021-12-04 12:07:05,937 INFO 127.0.0.1 - - [04/Dec/2021 12:07:05] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 12:29:45,178 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 12:29:56,005 INFO 127.0.0.1 - - [04/Dec/2021 12:29:56] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 12:30:17,381 INFO 127.0.0.1 - - [04/Dec/2021 12:30:17] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 12:31:40,737 INFO 127.0.0.1 - - [04/Dec/2021 12:31:40] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 12:31:55,654 INFO 127.0.0.1 - - [04/Dec/2021 12:31:55] "DELETE /account/5 HTTP/1.1" 200 -
2021-12-04 12:35:24,394 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 12:35:28,965 INFO 127.0.0.1 - - [04/Dec/2021 12:35:28] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 12:59:34,819 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 12:59:43,611 INFO 127.0.0.1 - - [04/Dec/2021 12:59:43] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 12:59:48,219 INFO 127.0.0.1 - - [04/Dec/2021 12:59:48] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 13:00:03,513 INFO 127.0.0.1 - - [04/Dec/2021 13:00:03] "GET /accounts HTTP/1.1" 200 -
2021-12-04 13:11:03,646 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:11:33,543 INFO 127.0.0.1 - - [04/Dec/2021 13:11:33] "GET /account/4 HTTP/1.1" 200 -
2021-12-04 13:11:44,974 INFO 127.0.0.1 - - [04/Dec/2021 13:11:44] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 13:16:01,442 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:16:12,089 INFO 127.0.0.1 - - [04/Dec/2021 13:16:12] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 13:16:16,395 INFO 127.0.0.1 - - [04/Dec/2021 13:16:16] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 13:25:26,876 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:25:30,789 INFO 127.0.0.1 - - [04/Dec/2021 13:25:30] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 13:25:39,738 INFO 127.0.0.1 - - [04/Dec/2021 13:25:39] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 13:25:44,618 ERROR Exception on /accounts/3 [GET]
Traceback (most recent call last):
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/Users/dlanderos/PycharmProjects/Project_0/venv/lib/python3.7/site-packages/flask/app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'get_all_customer_bank_accounts_by_id' did not return a valid response. The function either returned None or ended without a return statement.
2021-12-04 13:25:44,622 INFO 127.0.0.1 - - [04/Dec/2021 13:25:44] "[35m[1mGET /accounts/3 HTTP/1.1[0m" 500 -
2021-12-04 13:26:43,351 INFO 127.0.0.1 - - [04/Dec/2021 13:26:43] "GET /account/2 HTTP/1.1" 200 -
2021-12-04 13:26:49,232 INFO 127.0.0.1 - - [04/Dec/2021 13:26:49] "GET /account/55 HTTP/1.1" 200 -
2021-12-04 13:27:00,639 INFO 127.0.0.1 - - [04/Dec/2021 13:27:00] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 13:39:21,466 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:39:57,567 INFO 127.0.0.1 - - [04/Dec/2021 13:39:57] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 13:44:34,774 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:44:41,752 INFO 127.0.0.1 - - [04/Dec/2021 13:44:41] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 13:47:25,718 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:47:42,814 INFO 127.0.0.1 - - [04/Dec/2021 13:47:42] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 13:47:47,146 INFO 127.0.0.1 - - [04/Dec/2021 13:47:47] "GET /accounts/10 HTTP/1.1" 200 -
2021-12-04 13:48:30,676 INFO 127.0.0.1 - - [04/Dec/2021 13:48:30] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 13:48:35,957 INFO 127.0.0.1 - - [04/Dec/2021 13:48:35] "GET /accounts/20 HTTP/1.1" 200 -
2021-12-04 13:50:44,103 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:50:54,643 INFO 127.0.0.1 - - [04/Dec/2021 13:50:54] "GET /accounts/21 HTTP/1.1" 200 -
2021-12-04 13:51:00,735 INFO 127.0.0.1 - - [04/Dec/2021 13:51:00] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 13:51:03,205 INFO 127.0.0.1 - - [04/Dec/2021 13:51:03] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 13:51:28,432 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 13:51:33,160 INFO 127.0.0.1 - - [04/Dec/2021 13:51:33] "GET /accounts/2 HTTP/1.1" 200 -
2021-12-04 14:16:32,554 INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-12-04 14:17:11,533 INFO 127.0.0.1 - - [04/Dec/2021 14:17:11] "POST /customer HTTP/1.1" 200 -
2021-12-04 14:17:56,482 INFO 127.0.0.1 - - [04/Dec/2021 14:17:56] "POST /customer HTTP/1.1" 200 -
2021-12-04 14:18:20,487 INFO 127.0.0.1 - - [04/Dec/2021 14:18:20] "POST /customer HTTP/1.1" 200 -
2021-12-04 14:18:45,409 INFO 127.0.0.1 - - [04/Dec/2021 14:18:45] "POST /customer HTTP/1.1" 200 -
2021-12-04 14:19:14,049 INFO 127.0.0.1 - - [04/Dec/2021 14:19:14] "POST /customer HTTP/1.1" 200 -
2021-12-04 14:20:04,601 INFO 127.0.0.1 - - [04/Dec/2021 14:20:04] "GET /customer/3 HTTP/1.1" 200 -
2021-12-04 14:20:19,083 INFO 127.0.0.1 - - [04/Dec/2021 14:20:19] "GET /customer/30 HTTP/1.1" 200 -
2021-12-04 14:20:26,327 INFO 127.0.0.1 - - [04/Dec/2021 14:20:26] "GET /customers HTTP/1.1" 200 -
2021-12-04 14:21:10,673 INFO 127.0.0.1 - - [04/Dec/2021 14:21:10] "PATCH /customer/2 HTTP/1.1" 200 -
2021-12-04 14:21:47,490 INFO 127.0.0.1 - - [04/Dec/2021 14:21:47] "PATCH /customer/3 HTTP/1.1" 200 -
2021-12-04 14:22:36,062 INFO 127.0.0.1 - - [04/Dec/2021 14:22:36] "DELETE /customer/3 HTTP/1.1" 200 -
2021-12-04 14:23:01,871 INFO 127.0.0.1 - - [04/Dec/2021 14:23:01] "POST /account HTTP/1.1" 200 -
2021-12-04 14:23:05,582 INFO 127.0.0.1 - - [04/Dec/2021 14:23:05] "POST /account HTTP/1.1" 200 -
2021-12-04 14:23:27,149 INFO 127.0.0.1 - - [04/Dec/2021 14:23:27] "POST /account HTTP/1.1" 200 -
2021-12-04 14:23:28,393 INFO 127.0.0.1 - - [04/Dec/2021 14:23:28] "POST /account HTTP/1.1" 200 -
2021-12-04 14:23:40,373 INFO 127.0.0.1 - - [04/Dec/2021 14:23:40] "POST /account HTTP/1.1" 200 -
2021-12-04 14:23:41,618 INFO 127.0.0.1 - - [04/Dec/2021 14:23:41] "POST /account HTTP/1.1" 200 -
2021-12-04 14:24:06,194 INFO 127.0.0.1 - - [04/Dec/2021 14:24:06] "POST /deposit/1 HTTP/1.1" 200 -
2021-12-04 14:24:36,932 INFO 127.0.0.1 - - [04/Dec/2021 14:24:36] "POST /deposit/2 HTTP/1.1" 200 -
2021-12-04 14:25:30,561 INFO 127.0.0.1 - - [04/Dec/2021 14:25:30] "POST /withdraw/2 HTTP/1.1" 200 -
2021-12-04 14:25:51,486 INFO 127.0.0.1 - - [04/Dec/2021 14:25:51] "POST /withdraw/2 HTTP/1.1" 200 -
2021-12-04 14:26:19,145 INFO 127.0.0.1 - - [04/Dec/2021 14:26:19] "POST /withdraw/2 HTTP/1.1" 200 -
2021-12-04 14:26:45,042 INFO 127.0.0.1 - - [04/Dec/2021 14:26:45] "POST /transfer/2/1 HTTP/1.1" 200 -
2021-12-04 14:27:23,887 INFO 127.0.0.1 - - [04/Dec/2021 14:27:23] "POST /transfer/2/1 HTTP/1.1" 200 -
2021-12-04 14:27:37,303 INFO 127.0.0.1 - - [04/Dec/2021 14:27:37] "GET /account/4 HTTP/1.1" 200 -
2021-12-04 14:27:46,128 INFO 127.0.0.1 - - [04/Dec/2021 14:27:46] "GET /accounts HTTP/1.1" 200 -
2021-12-04 14:28:06,132 INFO 127.0.0.1 - - [04/Dec/2021 14:28:06] "GET /accounts/1 HTTP/1.1" 200 -
2021-12-04 14:28:23,131 INFO 127.0.0.1 - - [04/Dec/2021 14:28:23] "DELETE /account/6 HTTP/1.1" 200 -
